# Generated by Django 3.2.9 on 2021-11-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=320, null=True)),
                ('status', models.CharField(choices=[(1, 'To do'), (2, 'Doing'), (3, 'Done')], default=1, max_length=1)),
            ],
        ),
    ]
